### ISSUE TITLE
Dockerイメージの圧縮 | 2020/11/14

### ISSUE THREAD

**Issue by asuhacoder** [Asuha-a/TechTrain#1]
# TechTrain Report

## Description

1つのDockerfileでbuild用のイメージと実行用のイメージを分ける
Goの実行ファイルのみをコンテナ内へ
Dockerイメージの圧縮

## Task List

- [x] 方法を検索
- [x] 圧縮方法
実行環境をalpineにしてイメージ内は実行ファイルだけにする。
goのbuildにもalpineイメージが使える
- [x] build用と実行用でなぜわざわざ分けるのか
buildに必要な環境を実行環境から削ぎ落とすことができる。
- [x] 実装
[Minimize product image size · Issue #24 · Asuha-a/URLShortener](https://github.com/Asuha-a/URLShortener/issues/24)
- [x] 成果調査
変更前のサイズ
gateway: 839MB
user: 839MB
変更後のサイズ
gateway: 22.4MB
user: 17.3MB

## References
[Hatena-Intern-2020-Template/Dockerfile at master · hatena/Hatena-Intern-2020-Template](https://github.com/hatena/Hatena-Intern-2020-Template/blob/master/services/account/Dockerfile)
[Use multi-stage builds | Docker Documentation](https://docs.docker.com/develop/develop-images/multistage-build/)

**Comment by GuiltyMorishita** [comment]
LGTM
