### ISSUE TITLE
NATとは

### ISSUE THREAD

**Issue by asuhacoder** [Asuha-a/TechTrain#7]
# TechTrain Report

## Description
#6 に引き続き、NATについて調べる。

## NAT

IPアドレスは別のIPアドレスに変換され、外部のユーザからは透過的である。
プライベートなIPアドレスはネットワーク外部では使用不可能なためパブリックなIPアドレスに変換する必要がある。
NATがなければパブリックIPアドレス1つごとにノード1つしか外部と通信できるようにならない。
そのため、ローカルネットワーク外部と通信するユーザが増える場合は特にNATの恩恵を受ける。
NATルータを複数用意することで一つが落ちた場合には別のNATルータを使って動かすことができる。

NATはNATとNAPTの2種類に分類できる。
NATはIPアドレスの変換のみだがNAPTはポートの変換などもできる。

## GCPにおけるNAT

GCPではNATを通った通信はIGWを通らずにインターネットに出ていくが、AWSではすべての通信はIGWを通る。

## Task List

- [x] RFCを探し読む
- [x] AWS以外のNAT

## References
[RFC 3022 - Traditional IP Network Address Translator (Traditional NAT)](https://tools.ietf.org/html/rfc3022)
[VPC Networking: GCP v.s. AWS. Comparing and contrasting Google Cloud… | by John Tucker | codeburst](https://codeburst.io/vpc-networking-gcp-v-s-aws-77a80bc7cfe2)

**Comment by GuiltyMorishita** [comment]
LGTM
