### ISSUE TITLE
DNSとは

### ISSUE THREAD

**Issue by asuhacoder** [Asuha-a/TechTrain#8]
# TechTrain Report

## Description

DNSはIPv4, IPv6の両方で使用される。
ユーザがホスト名やドメイン名を入力すると自動的にホスト名やIPアドレスが登録されたデータベースサーバが検索される。

DNSに問い合わせを行うホストやソフトウェアをリゾルバという。
リゾルバは最低でも1つ以上のネームサーバのIPアドレスを知らなければならない。
通常はその組織内のネームサーバを使用する。

DNSによる問い合わせの流れ
1. リゾルバが組織内のDNSサーバにIPアドレスを問い合わせる。
2. DNSサーバがIPアドレスを知っていれば返し、知らなければルートネームサーバに問い合わせる。
3. ルートネームサーバは目標のIPネームサーバのIPアドレスを返す。
4. 目標のネームサーバに問い合わせてドメインのIPアドレスを得る。
5. 通信を開始する。

## Task List

- [x] DNSとは

## References
[マスタリングTCP/IP―入門編―(第6版) (日本語)](https://www.amazon.co.jp/%E3%83%9E%E3%82%B9%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0TCP-IP%E2%80%95%E5%85%A5%E9%96%80%E7%B7%A8%E2%80%95-%E7%AC%AC6%E7%89%88-%E4%BA%95%E4%B8%8A-%E7%9B%B4%E4%B9%9F/dp/4274224473/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=)

**Comment by GuiltyMorishita** [comment]
LGTM
